### ISSUE TITLE
Sqlalchemy Turbodbc missing library: libsimdutf.so.9

### ISSUE THREAD

**Issue by amgcc** [dirkjonker/sqlalchemy-turbodbc#21]
After upgrading my conda environment today, package `simdutf` changed from version `5.4.15` to `5.5.0`.  Afterward, I started recieving errors with sqlalchemy about a missing library.  I'm not sure if this is something that needs to be fixed in the connector,  sqlalchemy or turbodbc because I don't understand the issue based on the error message.

```
    return sa.create_engine(conn_str, **kwargs)
../../../../envs/linux_py311/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py:375: in warned
    return fn(*args, **kwargs)
../../../../envs/linux_py311/lib/python3.11/site-packages/sqlalchemy/engine/create.py:518: in create_engine
    entrypoint = u._get_entrypoint()
../../../../envs/linux_py311/lib/python3.11/site-packages/sqlalchemy/engine/url.py:662: in _get_entrypoint
    cls = registry.load(name)
../../../../envs/linux_py311/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py:341: in load
    return impl.load()
../../../../envs/linux_py311/lib/python3.11/site-packages/importlib_metadata/__init__.py:209: in load
    module = import_module(match.group('module'))
../../../../envs/linux_py311/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../../../../envs/linux_py311/lib/python3.11/site-packages/sqlalchemy_turbodbc/dialect.py:24: in <module>
    from .connector import TurbodbcConnector
../../../../envs/linux_py311/lib/python3.11/site-packages/sqlalchemy_turbodbc/connector.py:16: in <module>
    from turbodbc import make_options
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    from importlib.metadata import version
    
>   from turbodbc_intern import Megabytes, Rows
E   ImportError: libsimdutf.so.9: cannot open shared object file: No such file or directory
```

**Comment by adamchen** [comment]
I don't think this is a `sqlalchemy-turbodbc` issue, unfortunately! Since 4.11 it seems that when using `turbodbc`, `simdutf` needs to be built and available on the host machine. I don't use Conda at all, but [this reply](https://github.com/blue-yonder/turbodbc/issues/420#issuecomment-2173932815) over on the `turbodbc` repo seems to imply that Conda distributes binary versions of `turbodbc` - perhaps all that is needed for now is to pin your `simdutf` version so it stays in line with the packaged version? Alternatively, you may have luck compiling the latest `simdutf` from source if you need the bleeding edge.

I'm going to close this issue as I don't think there's anything to do on the `sqlalchemy-turbodbc` side, but I'm be happy to reopen if I'm wrong.
